version: "3.3"

networks:
  i_network:
    driver: bridge
  iam_network:
    driver: bridge

services:

#  iam_postgresql:
#    image: postgres:11.5
#    container_name: iam-postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - "POSTGRES_USER=u_iam"
#      - "POSTGRES_PASSWORD=123456789"
#      - "POSTGRES_DB=iam"
#    volumes:
#      - ./iam/db/init.sql:/docker-entrypoint-initdb.d/schema.sql
#    networks:
#      - i_am

  postgresql:
    image: postgres:11.5
    container_name: icommerce-postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=u_icommerce"
      - "POSTGRES_PASSWORD=123456789"
      - "POSTGRES_DB=icommerce"
    networks:
      - i_network

  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: iam-es
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    networks:
      - i_network

  redis:
    image: redis:latest
    container_name: iam-redis
    ports:
      - "6379:6379"
    networks:
      - i_network

  zookeeper:
    image: bitnami/zookeeper:3.5.5
    container_name: iam-zookeeper
    ports:
      - "2181:2181"
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"
    networks:
      - i_network

  kafka:
    image: bitnami/kafka:2.3.0
    container_name: iam-kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092"
    depends_on:
      - zookeeper
    networks:
      - i_network

#  products:
##    build:
##      context: ./
##      dockerfile: Dockerfile
#    image: 'sample:dev'
#    container_name: 'nab_icommerce_products'
#    ports:
#      - 8080:8080
#    restart: unless-stopped
##    volumes:
##      - ./:/
##    env_file: ./products/.env
##    environment:
##      MONGO_URL: mongodb://products_db
##      MONGO_USER: ${PRODUCT_DB_USERNAME}
##      MONGO_PASSWORD: ${PRODUCT_DB_PASSWORD}
##      MONGO_DB: ${PRODUCT_DB_DATABASE}
##      AMQP_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq
#    command: java -jar dbtool-1.0.0.jar
#    depends_on:
#      - postgresql
#      - elasticsearch
#    networks:
#      - i_network
